<a href="https://colab.research.google.com/github/bhagath-ac07/machine-learning/blob/main/colab/healthcare-dataset-stroke-data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# healthcare stroke prediction using random_forest_classification


## Importing the libraries

In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Importing the dataset

In [9]:
dataset = pd.read_csv('/content/drive/MyDrive/healthcare-dataset-stroke-data.csv')
#dataset.replace(to_replace = np.nan, value = -99)
dataset['bmi'] = dataset['bmi'].replace(np.nan, -99)
dataset = pd.get_dummies(data=dataset, columns=['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status'])
# dataset['gender'] = dataset['gender'].replace('Male', 1)
# dataset['gender'] = dataset['gender'].replace('Female', 0)
# dataset['ever_married'] = dataset['ever_married'].replace('Yes', 1)
# dataset['ever_married'] = dataset['ever_married'].replace('No', 0)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(X[5])
print(y)
print(np.nan)

[5.6669e+04 8.1000e+01 0.0000e+00 0.0000e+00 1.8621e+02 2.9000e+01
 1.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00 1.0000e+00
 0.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
 1.0000e+00 0.0000e+00 1.0000e+00 0.0000e+00]
[0 0 0 ... 0 0 0]
nan


## Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [11]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4,5,6])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))
# X = np.array(ct.fit_transform(X))
# X = np.array(ct.fit_transform(X))


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train[0])
print(y_train)

[ 0.75249974 -1.12135412 -0.33178474 -0.23957284 -0.78988211 -0.01289497
 -0.22458539  0.83491141 -0.83446139 -0.01615637  1.38831751 -1.38831751
 -0.39447328 -0.05834409  0.87190624 -0.43511309 -0.39447328 -0.97372706
  0.97372706  1.52714568 -0.45823345 -0.76685373]
[0 0 0 ... 1 0 0]


## Training the Random Forest Classification model on the Training set

In [12]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10, criterion='entropy', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

## Predicting the Test set results

In [13]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [1 1]
 [0 0]]


## Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1087    0]
 [   2  189]]


0.9984350547730829